title: "Shurt Services"
description: "Consulting and development services for web, Python, and online community management"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
timezone: America/Denver
encoding: utf-8

plugins:
  - jekyll-include-cache

